"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const roleController_1 = require("../controllers/roleController");
const router = (0, express_1.Router)();
router.post('/create', roleController_1.createRole);
router.get('/getAll', roleController_1.getAllRoles);
router.get('/get/:id', roleController_1.getRoleById);
router.put('/update/:id', roleController_1.updateRole);
router.delete('/delete/:id', roleController_1.deleteRole);
exports.default = router;
